# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='belt_app.User'),
        ),
    ]
