# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_user_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
    ]
